name: "Snyk DotNet"
description: "Check your DotNet application for vulnerabilties using Snyk"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which Snyk command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to Snyk"
runs:
  using: "docker"
  image: "docker://garethr/snyk-dotnet:latest"
  args:
  - snyk
  - ${{ inputs.command }}
  - ${{ inputs.args }} 
