name: "Setup Snyk"
description: "Installs a specific version of Snyk"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  snyk-version:
    description: "Which Snyk version to install"
    default: latest
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/setup_snyk.sh ${{ inputs.snyk-version }}
      shell: bash
